cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIAZODODZI2GDAIPHX2
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/648770996788/javaSpringQueueOne
