management:
    endpoints:
        web:
            exposure:
                include: "*"
    security:
        enabled: false
---
spring:
    profiles: dev
server:
    port: 8000
---
spring:
    profiles: test
server:
    port: 9000
